config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    post 'login', to: 'authentication#login'
    post 'check_token', to: 'authentication#check_token'
    resources :discounts, only: :index
    resources :products do
      collection do
        get :last_update
        get :available
      end
    end
    resources :salesmen do
      collection do
        get :clients
        get :orders
      end
    end
    resources :orders
  end

  resources :clients do
    member do
      patch 'change_status'
    end
  end

  resources :orders do
    member do
      patch 'review'
    end
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'upload_file'
      patch 'massive_process'
    end
  end

  resources :discounts, except:[:show]

  resources :users do
    member do
      get :edit_password
      patch :update_password
      patch :change_status
    end
  end

  resources :zones

  get 'saint/pending'
  post 'saint/sincronize'
  get 'sales' => 'home#to_sales'
  get 'download/:filename' => 'home#download', as: :download_file

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated :user  do
      root 'home#index', as: :root_index
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Statusable
  devise :database_authenticatable, authentication_keys: {email: false, login: true}

  validates_presence_of(:name, :login, :saint_id)

  def self.types
    {
      'Superadmin': 'User::Superadmin',
      'Vendedor': 'User::Salesman',
      'Supervisor': 'User::Supervisor',
      'Administracion': 'User::Administration'
    }
  end

  def self.custom_authentication(params)
    user = where(login: params[:login].downcase).first
    return nil if user.nil? or user.inactive?
    if user.valid_password?(params[:password])
      user.generate_token!
      user
    else
      nil
    end
  end

  def guest?
    false
  end

  def generate_token!
    self.token = new_token_generated
    self.save
  end

  def new_token_generated
    Digest::SHA1.hexdigest( "#{Time.new.to_s}#{login}" )[0,32]

  end
end

app/models/user/administration.rb
class User::Administration < User
end

app/models/user/client.rb
class User::Client < User
end

app/models/user/guest.rb
class User::Guest
  include Draper::Decoratable
  def guest?
    true
  end
end

app/models/user/nil.rb
class User::Nil
  include Draper::Decoratable
end

app/models/user/salesman.rb
class User::Salesman < User
  has_many :clients, class_name: '::Client', through: :zones
  has_many :zones, class_name: '::Zone', foreign_key: 'user_id'

  has_many :orders, foreign_key: 'user_id'

  def salesman?
    true
  end
end

app/models/user/superadmin.rb
class User::Superadmin < User
  def superadmin?
    true
  end
end

app/models/user/supervisor.rb
class User::Supervisor < User
end

app/controllers/users_controller.rb
class UsersController < AuthenticationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,
                        :edit_password, :update_password, :change_status]

  def index
    @search = User.ransack(params[:q])
    @users = @search.result.page(params[:page]).decorate
  end

  def show
    @user = @user.decorate
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user), notice: 'El usuario ha sido creado exitosamente'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'El usuario ha sido actualizado exitosamente'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def edit_password
  end

  def update_password
    if @user.update(user_params_password)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def change_status
    @user.change_status!
    redirect_to user_path(@user)
  end
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:saint_id,:name,:login,
        :type, :status, :email)
    end

    def user_params_password
      params.require(:user).permit(:password,:password_confirmation)
    end
end

app/views/users/_form.html.slim
= form_for(user, url: url )do |f|
  - if user.errors.any?
    #error_explanation
      ul
        - user.errors.full_messages.each do |message|
          li = message
  .row
    .input-field.col-s6
      = f.label(:login)
      = f.text_field(:login, name:'user[login]')
  .row
    .input-field.col-s6
      = f.label(:name, "Nombre completo")
      = f.text_field(:name, name:'user[name]')
  .row
    .input-field.col-s6
      = f.label(:email, "Correo electronico")
      = f.email_field(:email, name:'user[email]')
  .row
    .input-field.col-s6
      = f.label(:saint_id, 'Codigo Saint')
      = f.text_field(:saint_id, name:'user[saint_id]')
  .row
    .input-field.col-s12
      = f.select(:type, User.types,  {},name:'user[type]')
      = f.label(:type, "Tipo de usuario")
  .row
    .input-field.col-s12
      = f.select(:status, User.status, {}, name:'user[status]')
      = f.label(:status, "Estatus")

  .row
    .actions
      = f.submit('Crear')
      = link_to 'Indice', users_path, class: 'btn grey'

app/views/users/edit.html.slim
h2 Editar Usuario

== render partial: 'form', locals:{user: @user, url: user_path(@user)}

app/views/users/edit_password.slim
h2 Editar contraseña

= form_for(@user, url: update_password_user_path(@user)) do |f|
  - if @user.errors.any?
    #error_explanation
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  .row
    .input-field.col-s6
      = f.label(:password)
      = f.password_field(:password, name:'user[password]')
  .row
    .input-field.col-s6
      = f.label(:password_confirmation)
      = f.password_field(:password_confirmation, name:'user[password_confirmation]')
  .row
    .actions
      = f.submit('Actualizar')
      = link_to 'Indice', users_path, class: 'btn grey'

app/views/users/index.html.slim
.row.header
  .col.s6
    h2 Usuarios
  .col.s3.offset-s3
    = link_to 'Nuevo Usuario', new_user_path, class: 'btn'

= paginate @users

table.striped
  thead
    tr
      th = sort_link(@search, :login)
      th = sort_link(@search, :name)
      th = sort_link(@search, :email)
      th Tipo de usuario
      th = sort_link(@search, :status)
      th acciones

  tbody
    - @users.each do |user|
      tr
        td= user.login
        td= user.name
        td= user.email
        th= user.type
        th= user.status
        td.actions-index
          = link_to user_path(user) do
            i.mdi-action-search
          = link_to edit_user_path(user) do
            i.mdi-editor-mode-edit
          = link_to user_path(user), method: :delete, data: { confirm: 'Esta seguro?' } do
            i.mdi-action-delete

= paginate @users

app/views/users/new.html.slim
h2 Usuario nuevo

== render partial: 'form', locals: {user: @user, url: users_path}

app/views/users/show.html.slim
h2 #{@user.name}
table.attributes-table
  tbody
    tr
      th Login
      td= @user.login
    tr
      th Email
      td= @user.email
    tr
      th Tipo
      td= @user.type
    tr
      th Estatus
      td= @user.status
    tr
      th Saint id
      td= @user.saint_id

.actions
  = link_to 'Editar', edit_user_path(@user), class: 'btn'
  = link_to 'Contraseña', edit_password_user_path, class: 'btn'
  = link_to @user.change_status, change_status_user_path(@user), method: :patch
  = link_to 'Volver', users_path, class: 'btn'