config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    post 'login', to: 'authentication#login'
    post 'check_token', to: 'authentication#check_token'
    resources :discounts, only: :index
    resources :products do
      collection do
        get :last_update
        get :available
      end
    end
    resources :salesmen do
      collection do
        get :clients
        get :orders
      end
    end
    resources :orders
  end

  resources :clients do
    member do
      patch 'change_status'
    end
  end

  resources :orders do
    member do
      patch 'review'
    end
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'upload_file'
      patch 'massive_process'
    end
  end

  resources :discounts, except:[:show]

  resources :users do
    member do
      get :edit_password
      patch :update_password
      patch :change_status
    end
  end

  resources :zones

  get 'saint/pending'
  post 'saint/sincronize'
  get 'sales' => 'home#to_sales'
  get 'download/:filename' => 'home#download', as: :download_file

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated :user  do
      root 'home#index', as: :root_index
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  include Statusable

  belongs_to :zone

  scope :user_id_eq, ->(user_id) { joins(zone: :user).where('users.id = ?', user_id) }
  scope :actives, -> { where(status: 1) }

  validates_uniqueness_of :saint_id
  validates_presence_of :cliente, :rif, :saint_id
  delegate :user, to: :zone, allow_nil: true

  def salesman
    user || User::Nil.new
  end

  def name
    cliente
  end
  private

  def self.ransackable_scopes(auth_object = nil)
    %i(user_id_eq)
  end
end

app/models/user/client.rb
class User::Client < User
end

app/controllers/api/clients_controller.rb
module Api
  class ClientsController < ApiController
#
    def show
      render json: client
    end

    private

    def client
      @client ||= Client.find(params[:id])
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < AuthenticationController
  before_action :set_client, only: [:show, :edit, :update, :destroy, :change_status]

  # GET /clients
  def index
    @q = Client.includes(zone: :user).ransack(params[:q])
    @clients = @q.result.page(params[:page]).decorate
  end

  # GET /clients/1
  def show
    @client = @client.decorate
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client fue creato exitosamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  def change_status
    @client.change_status!
    redirect_to client_path(@client)
  end
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def client_params
    params.require(:client).permit(:cliente, :cliente_optional, :zona_postal, :rif, :zone_id,
                   :description, :status, :direction, :contribuyente_especial,
                   :telefono,:saint_id)
  end
end

app/views/clients/_form.html.slim
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      ul
        - @client.errors.full_messages.each do |message|
          li = message
  .row
    .input-field.col.s12
      = f.text_field(:cliente)
      = f.label(:cliente)
    .input-field.col.s12
      = f.text_field(:cliente_optional)
      = f.label(:cliente_optional, 'Nombre opcional')
    .input-field.col.s12
      = f.text_field(:rif)
      = f.label(:rif)
    .input-field.col.s12
      = f.text_field(:telefono)
      = f.label(:telefono)
    .input-field.col.s12
      = f.text_field(:zona_postal)
      = f.label(:zona_postal )
    .input-field.col.s12
      = f.text_field(:saint_id)
      = f.label(:saint_id)
    .input-field.col.s12.check
        = f.check_box(:contribuyente_especial)
        = f.label(:contribuyente_especial)
    .input-field.col.s12
      = f.select(:status, Client.status)
      = f.label(:status, 'Estatus')
    .input-field.col.s12
      = f.collection_select(:zone_id, Zone.all, :id, :name, include_blank: 'Sin zona asignada')
  .actions
    = f.submit 'Enviar'
    = link_to 'Atras', clients_path

app/views/clients/edit.html.slim
h2 Editar Cliente

== render 'form'

app/views/clients/index.html.slim
.row.header
  .col.s6
    h2 Clientes
  .col.s3.offset-s3
    = link_to 'Nuevo Cliente', new_client_path, class: 'btn'

.row
  = search_form_for @q, class: 'col s12' do |f|
    .row
      .input-field.col.s3
        = f.search_field :cliente_cont
        = f.label :cliente_cont
      .input-field.col.s3
        = f.select(:zone_id_eq, options_from_collection_for_select(Zone.all, :id, :name, @q.zone_id_eq),include_blank: true)
        = f.label(:zone_id_eq, 'Buscar por zona')
      .input-field.col.s3
         = f.select(:user_id_eq, options_from_collection_for_select(User::Salesman.all, :id, :name, @q.user_id_eq),include_blank: true)
         = f.label(:user_id_eq, 'Buscar por vendedor')
      .col-s3
        = f.button'', class: 'btn-floating search-filter' do
          i.mdi-action-search
table.striped
  thead
    tr
      th = sort_link(@q, :cliente, 'Nombre')
      th = sort_link(@q, :zone_name, 'Zona')
      th = sort_link(@q, :user_name, 'Vendedor')
      th Descripcion
      th = sort_link(@q, :status, 'Estatus')
      th
  tbody
    - @clients.each do |client|
      tr
        td= client.cliente
        td= client.zone
        td= client.salesman
        td= client.description
        td= client.status
        td.actions-index
          = link_to client
            i.mdi-action-search
          = link_to edit_client_path(client) do
            i.mdi-editor-mode-edit
          = link_to client, data: {:confirm => 'Are you sure?'}, :method => :delete do
            i.mdi-action-delete

= paginate @clients

app/views/clients/new.html.slim
h2 Nuevo cliente

== render 'form'

app/views/clients/show.html.slim
p#notice = notice
h2 #{@client.cliente}
table.attributes-table
  tbody
    tr
      th Nombre secundario
      td= @client.cliente_optional
    tr
      th Telefono
      td= @client.telefono
    tr
      th zona
      td= @client.zone
    tr
      th Zona postal
      td= @client.zona_postal
    tr
      th Descripcion
      td= @client.description
    tr
      th rif
      td= @client.rif
    tr
      th Direccion
      th= @client.direction

    tr
      th saint_id
      td= @client.saint_id

    tr
      th Estatus
      td= @client.status

.actions
  = link_to 'Editar', edit_client_path(@client)
  = link_to @client.change_status, change_status_client_path(@client), method: :patch
  = link_to 'Volver', clients_path