config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    post 'login', to: 'authentication#login'
    post 'check_token', to: 'authentication#check_token'
    resources :discounts, only: :index
    resources :products do
      collection do
        get :last_update
        get :available
      end
    end
    resources :salesmen do
      collection do
        get :clients
        get :orders
      end
    end
    resources :orders
  end

  resources :clients do
    member do
      patch 'change_status'
    end
  end

  resources :orders do
    member do
      patch 'review'
    end
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'upload_file'
      patch 'massive_process'
    end
  end

  resources :discounts, except:[:show]

  resources :users do
    member do
      get :edit_password
      patch :update_password
      patch :change_status
    end
  end

  resources :zones

  get 'saint/pending'
  post 'saint/sincronize'
  get 'sales' => 'home#to_sales'
  get 'download/:filename' => 'home#download', as: :download_file

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated :user  do
      root 'home#index', as: :root_index
    end
  end
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  belongs_to :user
  has_many :clients

  validates_presence_of :name
end

app/controllers/zones_controller.rb
class ZonesController < AuthenticationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  def index
    @q = Zone.includes(:user).ransack(params[:q])
    @zones = @q.result.page(params[:page]).decorate
  end

  def show
    @zone = @zone.decorate
  end

  def new
    @zone = Zone.new
  end

  def edit
  end

  def create
    @zone = Zone.new(zone_params)
    if @zone.save
      redirect_to @zone, notice: 'Zone fue creato exitosamente.'
    else
      render :new
    end
  end

  def update
    if @zone.update(zone_params)
      redirect_to @zone, notice: 'Zone was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @zone.destroy
    redirect_to zones_url, notice: 'Zone was successfully destroyed.'
  end

  private
    def set_zone
      @zone = Zone.find(params[:id])
    end

    def zone_params
      params.require(:zone).permit(:name, :user_id, :description)
    end
end

app/views/zones/_form.html.slim
= form_for @zone do |f|
  - if @zone.errors.any?
      ul
        - @zone.errors.full_messages.each do |message|
          li = message

  .input-field
    = f.label :name, 'Nombre'
    = f.text_field :name
  .input-field
    = f.label :description, 'Descripcion'
    = f.text_area :description
  .input-field
    = f.collection_select(:user, User::Salesman.all, :id,:name)
    = f.label(:user, "Vendedor")

  .actions
    = f.submit 'Enviar'
    = link_to 'Atras', zones_path, class: 'btn grey'

app/views/zones/edit.html.slim
h2 Editando zona

== render 'form'

app/views/zones/index.html.slim
.row.header
  .col.s6
    h2 Zonas
  .col.s3.offset-s3
    = link_to 'Nueva Zona', new_zone_path, class: 'btn'

= paginate @zones

table.striped
  thead
    tr
      th = sort_link(@q, :name)
      th = sort_link(@q, :user_name)
      th Descripcion
      th Acciones
  tbody
    - @zones.each do |zone|
      tr
        td= zone.name
        td= zone.user_name
        td= zone.description
        td.actions-index
          = link_to zone_path(zone)
            i.mdi-action-search
          = link_to edit_zone_path(zone)
            i.mdi-editor-mode-edit
          = link_to zone_path(zone), method: :delete, data: { confirm: 'Are you sure?' } do
            i.mdi-action-delete

= paginate @zones

app/views/zones/new.html.slim
h1 Nueva zona

== render 'form'

app/views/zones/show.html.slim
table.attributes-table
  tbody
    tr
      th Nombre
      td= @zone
    tr
      th Description
      td= @zone.description
    tr
      th User
      td= @zone.user
    tr
h4 clientes
-if @zone.clients.any?
  ul.clients
    - @zone.clients.each do |client|
      li= client
-else
  p Aun no hay clientes para esta zona
.actions
  = link_to 'Editar', edit_zone_path(@zone)
  = link_to 'Atras', zones_path