config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    post 'login', to: 'authentication#login'
    post 'check_token', to: 'authentication#check_token'
    resources :discounts, only: :index
    resources :products do
      collection do
        get :last_update
        get :available
      end
    end
    resources :salesmen do
      collection do
        get :clients
        get :orders
      end
    end
    resources :orders
  end

  resources :clients do
    member do
      patch 'change_status'
    end
  end

  resources :orders do
    member do
      patch 'review'
    end
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'upload_file'
      patch 'massive_process'
    end
  end

  resources :discounts, except:[:show]

  resources :users do
    member do
      get :edit_password
      patch :update_password
      patch :change_status
    end
  end

  resources :zones

  get 'saint/pending'
  post 'saint/sincronize'
  get 'sales' => 'home#to_sales'
  get 'download/:filename' => 'home#download', as: :download_file

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated :user  do
      root 'home#index', as: :root_index
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  self.primary_key = "code"
  validates_numericality_of :price, greater_than: 0
  validates_presence_of :code, :description
  validates :code, exclusion: {in: ["''",'""']}

  monetize :price_cents

  scope :available, -> { where( 'units > 0') }

  def self.trademark
    Product.uniq.select('trademark').order('trademark').pluck(:trademark)
  end

  def self.last_update
    order(updated_at: :desc).limit(1).pluck(:updated_at).first.to_i
  end

  def as_json(options={})
    super(options).merge('price' => self.price.to_f)
  end

end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApiController

    def available
      render json: Product.available
    end

    def last_update
      render json: Product.last_update
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < AuthenticationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.page(params[:page]).decorate
  end

  # GET /products/1
  def show
    @product = @product.decorate
  end

  def upload_file
  end

  def massive_process
    FileToArray.new(file_params).to_run do |array|
      ParserProductsJob.new.perform(array)
    end
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def file_params
      params[:file][:productos]
    end
end

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.slim
.row.header
  .col.s6
    h2 Productos
  .col.s3.offset-s3
    = link_to 'Subir Archivo', upload_file_products_path, class: 'btn'
.row
  = search_form_for(@search) do |f|
    .row
      .input-field.col.s4
        = f.search_field :code_cont
        = f.label :code_cont, 'Codigo'
      .input-field.col.s4
        = f.select(:trademark_eq, Product.trademark)
        = f.label :trademark_eq, 'Marca'
      .input-field.col.s1.offset-s3
        = f.button '', class: 'btn-floating search-filter' do
          i.mdi-action-search
table
  thead
    tr
      th= sort_link(@search,:code, 'Codigo')
      th= sort_link(@search,:trademark, 'Marca')
      th Descripcion
      th= sort_link(@search, :units, 'Unidades')
      th= sort_link(@search, :price, 'Precio')

  tbody
    - @products.each do |product|
      tr
        td= product.code
        td= product.trademark
        td= product.description
        td= product.units
        td= product.price

= paginate @products

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice


= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path

app/views/products/upload_file.slim
h4 Actualizacion masiva
= form_for('file',  url: massive_process_products_path, html: {method: :patch, multipart: true}) do |f|
  .row
    .file-field.input-field.col.s12
      .btn
        span Archivo (CSV)
        = f.file_field('productos')
      .file-path-wrapper
        input.file-path.validate type="text"
    .col.s12.actions
      = f.submit 'Actualizar'
      = link_to 'Atras', products_path